In [1]:
import sys
sys.path.insert(0, '/home/cameron/Projects/hypso-package')

## Download Multiple NetCDF Files

In [2]:
# Download Files to relative folder  
from hypso import download_nc_files
            
download_nc_files(filename_list=["tibet_2022-09-29_0446Z.nc", "xaafuun_2023-09-11_0623Z-l1a.nc","vancouver_2023-05-25_1831Z-l1a.nc"],
                  download_dir="/home/cameron/Nedlastinger/")

Download Failed. HTTP Error 404: Not Found
Deleting tibet_2022-09-29_0446Z.nc
Download Failed. HTTP Error 404: Not Found
Deleting xaafuun_2023-09-11_0623Z-l1a.nc
Download Failed. HTTP Error 404: Not Found
Deleting vancouver_2023-05-25_1831Z-l1a.nc


## Read NetCDF File

In [3]:
# Import Satellite Object
from hypso import Hypso1
import os

# Define HYPSO Image File and the .points from QGIS (if available)
dir_path = '/home/cameron/Dokumenter/Data/erie'
l1a_nc_file = os.path.join(dir_path, 'erie_2022-07-20_1539Z-l1a.nc')
points_file = os.path.join(dir_path, 'erie_2022-07-20_1539Z-bin3.points')

# Create Satellite Object
satobj = Hypso1(path=l1a_nc_file, points_path=points_file, verbose=True)

[INFO] Loading L1a capture erie_2022-07-20_1539Z
[INFO] Capture spatial dimensions: (956, 684)
[INFO] Capture capture type: nominal
[INFO] Running georeferencing...
No image mode provided. Detected image mode: bin3
[INFO] Using UTM map: WGS 84 / UTM zone 16N EPSG: 32616


In [4]:
satobj.l1a_cube

<xarray.DataArray (y: 956, x: 684, band: 120)>
array([[[  798,  1371,  2267, ...,  6133,  6129,  6109],
        [  803,  1395,  2266, ...,  6089,  6036,  5969],
        [  789,  1389,  2295, ...,  6039,  5993,  6023],
        ...,
        [  845,  1477,  2530, ..., 10410, 10330, 10207],
        [  849,  1499,  2568, ..., 10492, 10325, 10163],
        [  851,  1485,  2562, ..., 10312, 10183, 10027]],

       [[  797,  1368,  2238, ...,  6203,  6238,  6164],
        [  799,  1361,  2272, ...,  6075,  6099,  6042],
        [  824,  1397,  2307, ...,  5998,  6098,  5985],
        ...,
        [  859,  1511,  2593, ..., 10166,  9997,  9933],
        [  864,  1492,  2548, ..., 10228, 10063, 10001],
        [  874,  1503,  2559, ..., 10241, 10038,  9919]],

       [[  800,  1393,  2286, ...,  6657,  6662,  6501],
        [  809,  1395,  2280, ...,  6537,  6481,  6364],
        [  830,  1372,  2255, ...,  6518,  6455,  6359],
        ...,
...
        ...,
        [  838,  1523,  2527, ..., 11201, 11016, 10895],
        [  816,  1483,  2543, ..., 11099, 10873, 10805],
        [  847,  1523,  2524, ..., 10900, 10782, 10614]],

       [[  781,  1342,  2231, ..., 10345, 10113,  9837],
        [  787,  1353,  2249, ..., 10295, 10171,  9778],
        [  784,  1355,  2245, ..., 10508, 10248,  9933],
        ...,
        [  900,  1591,  2650, ..., 10941, 10844, 10652],
        [  907,  1576,  2639, ..., 10837, 10796, 10594],
        [  887,  1567,  2636, ..., 10762, 10604, 10461]],

       [[  786,  1340,  2204, ..., 10118,  9993,  9658],
        [  785,  1357,  2235, ..., 10099,  9841,  9585],
        [  781,  1342,  2250, ..., 10313, 10069,  9769],
        ...,
        [  946,  1699,  2870, ..., 11082, 10919, 10855],
        [  952,  1740,  2813, ..., 11107, 10950, 10822],
        [  958,  1729,  2846, ..., 10958, 10741, 10741]]], dtype=uint16)
Coordinates:
  * y        (y) int64 0 1 2 3 4 5 6 7 8 ... 947 948 949 950 951 952 953 954 955
  * x        (x) int64 0 1 2 3 4 5 6 7 8 ... 675 676 677 678 679 680 681 682 683
  * band     (band) int64 0 1 2 3 4 5 6 7 8 ... 112 113 114 115 116 117 118 119
Attributes:
    level:        L1a
    units:        a.u.
    description:  Raw sensor value

## Get L1A datacube

In [5]:
l1a_cube = satobj.get_l1a_cube()

In [6]:
l1a_cube

<xarray.DataArray (y: 956, x: 684, band: 120)>
array([[[  798,  1371,  2267, ...,  6133,  6129,  6109],
        [  803,  1395,  2266, ...,  6089,  6036,  5969],
        [  789,  1389,  2295, ...,  6039,  5993,  6023],
        ...,
        [  845,  1477,  2530, ..., 10410, 10330, 10207],
        [  849,  1499,  2568, ..., 10492, 10325, 10163],
        [  851,  1485,  2562, ..., 10312, 10183, 10027]],

       [[  797,  1368,  2238, ...,  6203,  6238,  6164],
        [  799,  1361,  2272, ...,  6075,  6099,  6042],
        [  824,  1397,  2307, ...,  5998,  6098,  5985],
        ...,
        [  859,  1511,  2593, ..., 10166,  9997,  9933],
        [  864,  1492,  2548, ..., 10228, 10063, 10001],
        [  874,  1503,  2559, ..., 10241, 10038,  9919]],

       [[  800,  1393,  2286, ...,  6657,  6662,  6501],
        [  809,  1395,  2280, ...,  6537,  6481,  6364],
        [  830,  1372,  2255, ...,  6518,  6455,  6359],
        ...,
...
        ...,
        [  838,  1523,  2527, ..., 11201, 11016, 10895],
        [  816,  1483,  2543, ..., 11099, 10873, 10805],
        [  847,  1523,  2524, ..., 10900, 10782, 10614]],

       [[  781,  1342,  2231, ..., 10345, 10113,  9837],
        [  787,  1353,  2249, ..., 10295, 10171,  9778],
        [  784,  1355,  2245, ..., 10508, 10248,  9933],
        ...,
        [  900,  1591,  2650, ..., 10941, 10844, 10652],
        [  907,  1576,  2639, ..., 10837, 10796, 10594],
        [  887,  1567,  2636, ..., 10762, 10604, 10461]],

       [[  786,  1340,  2204, ..., 10118,  9993,  9658],
        [  785,  1357,  2235, ..., 10099,  9841,  9585],
        [  781,  1342,  2250, ..., 10313, 10069,  9769],
        ...,
        [  946,  1699,  2870, ..., 11082, 10919, 10855],
        [  952,  1740,  2813, ..., 11107, 10950, 10822],
        [  958,  1729,  2846, ..., 10958, 10741, 10741]]], dtype=uint16)
Coordinates:
  * y        (y) int64 0 1 2 3 4 5 6 7 8 ... 947 948 949 950 951 952 953 954 955
  * x        (x) int64 0 1 2 3 4 5 6 7 8 ... 675 676 677 678 679 680 681 682 683
  * band     (band) int64 0 1 2 3 4 5 6 7 8 ... 112 113 114 115 116 117 118 119
Attributes:
    level:        L1a
    units:        a.u.
    description:  Raw sensor value

## Generate L1B datacube

In [7]:
satobj.generate_l1b_cube()

l1b_cube = satobj.get_l1b_cube()

[INFO] Running calibration routines...
[INFO] Running radiometric calibration...
[INFO] Running smile correction...
[INFO] Running destriping correction...


In [8]:
l1b_cube

<xarray.DataArray (y: 956, x: 684, band: 120)>
array([[[  0.        ,   0.        ,   0.        , ...,  80.92908708,
          83.36050147,  85.31312168],
        [  0.        ,   0.        ,   0.        , ...,  82.58820464,
          84.3739673 ,  85.76266997],
        [  0.        ,   0.        ,   0.        , ...,  80.71754832,
          82.45226703,  85.77154641],
        ...,
        [  0.        ,   0.        ,   0.        , ..., 124.13864657,
         125.41705521, 127.49429348],
        [  0.        ,   0.        ,   0.        , ..., 125.23858932,
         124.880285  , 127.34181532],
        [  0.        ,   0.        ,   0.        , ..., 122.28327857,
         123.46631668, 125.40393659]],

       [[  0.        ,   0.        ,   0.        , ...,  81.86477268,
          84.87114042,  86.02675158],
        [  0.        ,   0.        ,   0.        , ...,  82.38707409,
          85.30537161,  86.7623431 ],
        [  0.        ,   0.        ,   0.        , ...,  80.1769776 ,
          83.9588456 ,  85.01326631],
...
        [  0.        ,   0.        ,   0.        , ..., 130.47358318,
         131.53242922, 132.47016163],
        [  0.        ,   0.        ,   0.        , ..., 129.59498001,
         131.22388076, 130.13984233],
        [  0.        ,   0.        ,   0.        , ..., 127.63399969,
         128.51615624, 131.54733659]],

       [[  0.        ,   0.        ,   0.        , ..., 134.08915929,
         136.4922069 , 135.28154078],
        [  0.        ,   0.        ,   0.        , ..., 137.51510499,
         138.17522899, 138.23965472],
        [  0.        ,   0.        ,   0.        , ..., 138.45798246,
         139.14346152, 139.53420511],
        ...,
        [  0.        ,   0.        ,   0.        , ..., 132.09487744,
         132.34786221, 137.78614271],
        [  0.        ,   0.        ,   0.        , ..., 132.48917552,
         132.82446989, 135.31264266],
        [  0.        ,   0.        ,   0.        , ..., 129.55967535,
         130.45974799, 136.78471057]]])
Coordinates:
  * y        (y) int64 0 1 2 3 4 5 6 7 8 ... 947 948 949 950 951 952 953 954 955
  * x        (x) int64 0 1 2 3 4 5 6 7 8 ... 675 676 677 678 679 680 681 682 683
  * band     (band) int64 0 1 2 3 4 5 6 7 8 ... 112 113 114 115 116 117 118 119
Attributes:
    level:        L1b
    units:        $mW\cdot  (m^{-2}  \cdot sr^{-1} nm^{-1})$
    description:  Radiance (L)

## Generate geometry

In [9]:
satobj.generate_geometry()

[INFO] Running geometry computation...
ECI position samples: 1631
Quaternion samples: 1631
ADCS time range: 1658330880.000000 to 1658331778.250000
Frame time range: 1658331554.791878 to 1658331598.200969
173 sample(s) inside frame time range
Interpolating 956 frames
Spatial dimensions: 956 frames/lines, 684 pixels/samples
Computing pixel latitude and longitude coordinates...
Interpolating pixel coordinate gaps...
Using geometry-computed latitude and longitude values
Computing local angles (sun and satellite azimuth and zenith angles)...
Image Center (lat,lon): (41.82761	-83.08504)
Image Center elevation angle: 63.52887
Image Center off-nadir angle: 32.72877


## Generate 6sv1 L2A datacube

In [10]:
satobj.generate_l2a_cube(product_name='6sv1')

l2a_cube = satobj.get_l2a_cube()

[INFO] Running 6SV1 atmospheric correction

-------  Py6S Atmospheric Correction  ----------
ROI:
Max Lat: 43.12644389364998  Min Lat: 40.36988390355103
Max Lon: -82.67700617437025  Min Lon: -84.15470201879344


100%|██████████| 120/120 [00:52<00:00,  2.30it/s]


In [11]:
l2a_cube

<xarray.DataArray (y: 956, x: 684, band: 120)>
array([[[-0.33597375, -0.3145017 , -0.30303441, ...,  0.27399502,
          0.2825262 ,  0.29566688],
        [-0.33597375, -0.3145017 , -0.30303441, ...,  0.27999375,
          0.28618484,  0.29732186],
        [-0.33597375, -0.3145017 , -0.30303441, ...,  0.27323018,
          0.27924745,  0.29735454],
        ...,
        [-0.33597375, -0.3145017 , -0.30303441, ...,  0.43022403,
          0.43435153,  0.45095378],
        [-0.33597375, -0.3145017 , -0.30303441, ...,  0.434201  ,
          0.43241378,  0.45039244],
        [-0.33597375, -0.3145017 , -0.30303441, ...,  0.42351574,
          0.42730931,  0.44325828]],

       [[-0.33597375, -0.3145017 , -0.30303441, ...,  0.2773781 ,
          0.28797965,  0.29829406],
        [-0.33597375, -0.3145017 , -0.30303441, ...,  0.27926654,
          0.28954724,  0.30100208],
        [-0.33597375, -0.3145017 , -0.30303441, ...,  0.27127569,
          0.28468624,  0.29456299],
...
        [-0.33597375, -0.3145017 , -0.30303441, ...,  0.45312871,
          0.4564282 ,  0.46927208],
        [-0.33597375, -0.3145017 , -0.30303441, ...,  0.44995202,
          0.45531433,  0.46069318],
        [-0.33597375, -0.3145017 , -0.30303441, ...,  0.44286187,
          0.44553937,  0.46587476]],

       [[-0.33597375, -0.3145017 , -0.30303441, ...,  0.46620123,
          0.47433314,  0.47962196],
        [-0.33597375, -0.3145017 , -0.30303441, ...,  0.47858812,
          0.48040889,  0.49051204],
        [-0.33597375, -0.3145017 , -0.30303441, ...,  0.4819972 ,
          0.48390424,  0.49527783],
        ...,
        [-0.33597375, -0.3145017 , -0.30303441, ...,  0.45899068,
          0.45937194,  0.48884247],
        [-0.33597375, -0.3145017 , -0.30303441, ...,  0.46041631,
          0.4610925 ,  0.47973646],
        [-0.33597375, -0.3145017 , -0.30303441, ...,  0.44982437,
          0.45255579,  0.48515577]]])
Coordinates:
  * y        (y) int64 0 1 2 3 4 5 6 7 8 ... 947 948 949 950 951 952 953 954 955
  * x        (x) int64 0 1 2 3 4 5 6 7 8 ... 675 676 677 678 679 680 681 682 683
  * band     (band) int64 0 1 2 3 4 5 6 7 8 ... 112 113 114 115 116 117 118 119
Attributes:
    level:        L2a
    units:        sr^{-1}
    description:  Reflectance (Rrs)
    correction:   6sv1

## Write L1b NetCDF

In [13]:
satobj.write_l1b_nc_file(overwrite=True)

In [14]:
satobj.write_l2a_nc_file(overwrite=True)

In [29]:
nc_file_path = satobj.l1b_nc_file


In [30]:
import netCDF4 as nc
import numpy as np

with nc.Dataset(nc_file_path, format="NETCDF4") as f:
    group = f.groups["products"]
    # 16-bit according to Original data Capture
    cube = np.array(group.variables["Lt"][:], dtype='double')
    #cube = np.array(group.variables["Lt"][:], dtype='uint16')


In [32]:
cube

array([[[  0.        ,   0.        ,   0.        , ...,  80.92908708,
          83.36050147,  85.31312168],
        [  0.        ,   0.        ,   0.        , ...,  82.58820464,
          84.3739673 ,  85.76266997],
        [  0.        ,   0.        ,   0.        , ...,  80.71754832,
          82.45226703,  85.77154641],
        ...,
        [  0.        ,   0.        ,   0.        , ..., 124.13864657,
         125.41705521, 127.49429348],
        [  0.        ,   0.        ,   0.        , ..., 125.23858932,
         124.880285  , 127.34181532],
        [  0.        ,   0.        ,   0.        , ..., 122.28327857,
         123.46631668, 125.40393659]],

       [[  0.        ,   0.        ,   0.        , ...,  81.86477268,
          84.87114042,  86.02675158],
        [  0.        ,   0.        ,   0.        , ...,  82.38707409,
          85.30537161,  86.7623431 ],
        [  0.        ,   0.        ,   0.        , ...,  80.1769776 ,
          83.9588456 ,  85.01326631],
        ...,


In [26]:
cube

array([[[  0,   0,   0, ...,  80,  83,  85],
        [  0,   0,   0, ...,  82,  84,  85],
        [  0,   0,   0, ...,  80,  82,  85],
        ...,
        [  0,   0,   0, ..., 124, 125, 127],
        [  0,   0,   0, ..., 125, 124, 127],
        [  0,   0,   0, ..., 122, 123, 125]],

       [[  0,   0,   0, ...,  81,  84,  86],
        [  0,   0,   0, ...,  82,  85,  86],
        [  0,   0,   0, ...,  80,  83,  85],
        ...,
        [  0,   0,   0, ..., 120, 121, 125],
        [  0,   0,   0, ..., 121, 122, 125],
        [  0,   0,   0, ..., 121, 121, 125]],

       [[  0,   0,   0, ...,  87,  90,  90],
        [  0,   0,   0, ...,  88,  90,  91],
        [  0,   0,   0, ...,  87,  88,  90],
        ...,
        [  0,   0,   0, ..., 118, 117, 120],
        [  0,   0,   0, ..., 118, 119, 119],
        [  0,   0,   0, ..., 120, 120, 122]],

       ...,

       [[  0,   0,   0, ..., 138, 140, 138],
        [  0,   0,   0, ..., 141, 143, 141],
        [  0,   0,   0, ..., 141, 143, 143